name: my_documents
description: "My Documents app for managing personal documents."
publish_to: 'none'

version: 1.0.0+29469227

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI / UX
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.0.0

  # State management
  flutter_bloc: ^9.1.1

  # Storage & persistence
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  path_provider: ^2.1.5
  path: ^1.9.1

  # Files & media
  file_picker: ^10.3.3
  open_filex: ^4.7.0
  image_picker: ^1.2.0
  archive: ^4.0.7
  cunning_document_scanner: ^1.4.0

  # Security & auth
  local_auth: ^2.3.0
  jailbreak_root_detection: ^1.2.0+1
  crypto: ^3.0.6

  # System / platform
  window_manager: ^0.5.1
  meta: ^1.16.0

  # Notifications & sharing
  awesome_notifications: ^0.10.1
  share_plus: ^12.0.1

  # Internationalization
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
 