name: Build Flutter APK (Release)

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - uses: actions/checkout@v4

      # 2️⃣ Установка Java
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Установка Flutter с кэшем
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.6'
          cache: true

      # 4️⃣ Кэш Gradle + Android SDK/NDK
      - name: Cache Gradle & Android SDK/NDK
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle
            ~/.android
            /usr/local/lib/android/sdk
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 5️⃣ Получение зависимостей Flutter
      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Generate localizations
        run: flutter gen-l10n

      # 6️⃣ Подготовка keystore
      - name: Prepare keystore
        env:
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ENCODED_KEYSTORE: ${{ secrets.UPLOAD_KEYSTORE_BASE64 }}
        run: |
          mkdir -p android/app
          echo "$ENCODED_KEYSTORE" | base64 --decode > android/app/upload-keystore.jks
          cat > android/key.properties <<EOF
          storePassword=$STORE_PASSWORD
          keyPassword=$KEY_PASSWORD
          keyAlias=$KEY_ALIAS
          storeFile=upload-keystore.jks
          EOF

      # 7️⃣ Сборка split APK + оптимизации
      - name: Build APK (split per ABI)
        run: |
          flutter build apk \
            --release \
            --split-per-abi 

      # 8️⃣ Генерация уникального тега
      - name: Generate tag
        id: tag
        run: |
          TAG="build-$(date +'%Y-%m-%d-%H-%M')"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      # 9️⃣ Создание GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Release ${{ steps.tag.outputs.tag }}
          files: |
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
